# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "likhita-patra"
version = "0.1.0"
entrypoint = "src/likhita-patra.typ"
authors = ["Nandakumar Chandrasekhar"]
license = "Unlicense"
description = "A Typst template for writing letters containing multiple signatures, images, footnotes and enclosures."
repository = "https://github.com/nandac/likhita-patra"
keywords = ["letter", "templates", "signatures", "footers", "personal", "formal", "professional"]
categories = ["office", "layout"]
compiler = "0.12.0"
exclude = [
	".github",
	"docs",
	"scripts",
	"tests",
	".typstignore",
	"Justfile",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
