# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "letterloom"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Nandakumar Chandrasekhar"]
license = "Unlicense"
description = "A Typst template for writing letters containing multiple signatures, figures, footnotes and enclosures."
# homepage = ""
repository = "https://github.com/nandac/letterloom"
keywords = ["letter"]
categories = ["office", "layout"]
disciplines = ["communication"]
compiler = "0.13.0"
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
  "thumbnail-dark.svg",
  "thumbnail-light.svg",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"

# [tool.mytool]
# foo = "bar"
